# File: .prettierrc.yaml
# Aligns with Python/Ruff standards (120 chars)
tabWidth: 4
useTabs: false
printWidth: 120
semi: true
singleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
endOfLine: "lf"

overrides:
  - files: ["*.yml", "*.yaml"]
    options:
      tabWidth: 2
